'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("POS_Fast_Food_Shop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdeZ_Surprising_Soy_Drink_800ml_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdeZ Surprising Soy Drink 800ml.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beverage_Can_Coca_Cola_330ml_Tall_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beverage Can Coca-Cola 330ml Tall.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beverage_Can_Fanta_Mezzo_330ml_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beverage Can Fanta Mezzo 330ml.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beverage_Can_Sprite_330ml_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beverage Can Sprite 330ml.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cartoon_Chicken_Bucket_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cartoon Chicken Bucket.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cartoon_French_fries_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cartoon French fries.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chips_Packaging_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chips Packaging.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Disposable_Cup_with_Coffee_G06_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disposable Cup with Coffee.G06.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Doritos_Cool_Ranch_Chips_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doritos Cool Ranch Chips.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Food_Restaurant__24_Hours_G02_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Food Restaurant  24 Hours.G02.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Food_Restaurant__24_Hours_G02_watermarked1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Food Restaurant  24 Hours.G02.watermarked1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fried_Eggs_In_A_Pan_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fried Eggs In A Pan.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fried_Shrimp_Noodle_Soup_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fried Shrimp Noodle Soup.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Dog_with_Mustard_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot Dog with Mustard.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lays_Classic_Potato_Chips_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lays Classic Potato Chips.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lorenz_Chipsletten_Mediterranean_Paprika_100g_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lorenz Chipsletten Mediterranean Paprika 100g.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property New_York_Style_Pizza_G01_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New York Style Pizza.G01.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Potato_Wedges_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Potato Wedges.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Potato_Wedges_G10_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Potato Wedges.G10.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Salad_Set_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Salad Set.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sausage_Croissant_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sausage Croissant.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Soju_Original_Alcoholic_Beverage_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Soju Original Alcoholic Beverage.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splashone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splashone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Veggie_Burger_G16_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Veggie Burger.G16.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wavy_Lays_Original_Potato_Chips_G03_watermarked_2k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wavy Lays Original Potato Chips.G03.watermarked.2k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
